### ISSUE TITLE
The Data Loading Parquet example fails with Spark 1.5.0 or above

### ISSUE THREAD

**Issue by jtfogarty** [arunma/ScalaDataAnalysisCookbook#4]
I copied your chapter3-data-loading-parquet project and modified the build.sbt file setting

```
sparkVersion="1.5.0"
rather than
sparkVersion="1.4.1"
```

I get the below error when I run;

> chapter3-data-loading-parquet-1.5.0/studentAvroPq/part-r-00000.parquet invalid: all the files must be contained in the root studentAvroPq

should I change the version of apache avro, twitter parquet-avro or chill-avro when i change the spark version?  My goal is to use spark 1.6.1 and Scala 2.11.7.

I did find this [jira](https://issues.apache.org/jira/browse/SPARK-11620)

Thanks for your help!

**Comment by arunma** [comment]
Thanks a lot, Jeff.
